/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a95003e4544dc1597fea683a1ac9a81c)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	BETTER_AUTH_SECRET: string;
	ADMIN_EMAIL: string;
	ADMIN_PASSWORD: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "ADMIN_EMAIL" | "ADMIN_PASSWORD">> {}
}
